import pyautogui
import time
import pandas
pyautogui.PAUSE = 1.0
pyautogui.press('win')
pyautogui.write('chrome')
pyautogui.press('enter')
time.sleep(5)
pyautogui.click(x=252, y=83)
pyautogui.write('https://dlp.hashtagtreinamentos.com/python/intensivao/login')
pyautogui.press('enter')
time.sleep(5)
pyautogui.click(x=693, y=515)
pyautogui.hotkey('ctrl','a')
pyautogui.write('emailteste@gmail.com')
pyautogui.click(x=617, y=631)
pyautogui.write('ninja007')
pyautogui.click(945, y=721)
time.sleep(5)
tabela = pandas.read_csv('produtos.csv')
print(tabela)
for linha in tabela.index:

    pyautogui.click(x=600, y=361)
    pyautogui.hotkey('ctrl','a')
    produto = str(tabela.loc[linha,'codigo'])
    pyautogui.write(produto)
    pyautogui.press('tab')
    marca = str(tabela.loc[linha,'marca'])
    pyautogui.write(marca)
    pyautogui.press('tab')
    tipo= str(tabela.loc[linha,'tipo'])
    pyautogui.write(tipo)
    pyautogui.press('tab')
    categoria = str(tabela.loc[linha,'categoria'])
    pyautogui.write(categoria)
    pyautogui.press('tab')
    preco= str(tabela.loc[linha,'preco_unitario'])
    pyautogui.write(preco)
    pyautogui.press('tab')
    custo = str(tabela.loc[linha,'custo'])
    pyautogui.write(custo)
    pyautogui.press('tab')
    obs = str(tabela.loc[linha,'obs'])
    pyautogui.write(obs)
    if obs != "nan":
        pyautogui.write('sem obs')
    pyautogui.press('tab')
    pyautogui.press('enter')
    pyautogui.scroll(5000)

