import pyautogui
import time
import pandas
pyautogui.PAUSE = 1.0
pyautogui.press('win')
pyautogui.write('chrome')
pyautogui.press('enter')
time.sleep(5)
pyautogui.click(x=252, y=83)
pyautogui.write('https://dlp.hashtagtreinamentos.com/python/intensivao/login')
pyautogui.press('enter')
time.sleep(5)
pyautogui.click(x=693, y=515)
pyautogui.hotkey('ctrl','a')
pyautogui.write('emailteste@gmail.com')
pyautogui.click(x=617, y=631)
pyautogui.write('ninja007')
pyautogui.click(945, y=721)
time.sleep(5)
tabela = pandas.read_csv('produtos.csv')
print(tabela)
pyautogui.PAUSE = 0.5
pyautogui.click(x=600, y=361)
pyautogui.write('codigo')
pyautogui.press('tab')
pyautogui.write('marca')
pyautogui.press('tab')
pyautogui.write('tipo')
pyautogui.press('tab')
pyautogui.write('categoria')
pyautogui.press('tab')
pyautogui.write('preco')
pyautogui.press('tab')
pyautogui.write('custo')
pyautogui.press('tab')
pyautogui.write('obs')

